const $=s=>document.querySelector(s), euro=n=>`€${n.toFixed(2)}`;
const price=$('#price'),price2=$('#price2'),mix=$('#mix');
function linePath(fn){let d='';for(let i=0;i<=10;i++){let x=30+i*55,y=205-fn(i/10)*165;d+=(i?'L':'M')+x+' '+y}return d}
function update(p=+price.value){price.value=p;price2.value=p;let acceptance=p<1.9?61.7-(p-1.5)*9:p<2.3?51.7-(p-2.19)*18:26.7-(p-2.59)*6;acceptance=Math.max(18,Math.min(68,acceptance));let retail=.4+(p-1.79)*.575, gym=.81+(p-1.79)*.8,dtc=.77+(p-1.79)*.96,owned=+mix.value/100;let profit=owned*((gym+dtc)/2)+(1-owned)*retail,ratio=2.9+(owned-.6)*.4-(Math.abs(p-2.19)*.3);$('#headPrice').textContent=euro(p);$('#priceOut').textContent=euro(p);$('#summaryPrice').textContent=euro(p);$('#acceptance').textContent=acceptance.toFixed(1)+'%';$('#profit').textContent=euro(profit);$('#ratio').textContent=ratio.toFixed(1)+'×';$('#mixOut').textContent=mix.value+'% owned';$('#action').textContent=p<2?'Use this only as a time-boxed acquisition offer; protect premium shelf price.':p>2.45?'Reserve this for a premium pack or post-proof upsell.':'Protect '+euro(p)+' and validate repeat before opening grocery distribution.';$('#econTable').innerHTML=[['Retail / Grocery',p*.57,.43,retail],['Gym & Office',p*.87,.13,gym],['DTC Online',p*.96,.04,dtc]].map(r=>`<tr><td>${r[0]}</td><td>${euro(r[1])}</td><td>${(r[2]*100).toFixed(0)}%</td><td class="good">${euro(r[3])}</td></tr>`).join('');let pos=(p-1.5)/1.5*100;$('#brandPin').style.left=pos+'%';$('#handle').setAttribute('x1',30+pos*5.5);$('#handle').setAttribute('x2',30+pos*5.5);$('#fixedLine').setAttribute('d',linePath(t=>.35+.55*t));$('#elasticLine').setAttribute('d',linePath(t=>.2+.78*t-.28*t*t))}
price.addEventListener('input',()=>update());price2.addEventListener('input',e=>update(+e.target.value));mix.addEventListener('input',()=>update());update();
$('#theme').addEventListener('click',()=>{document.body.classList.toggle('dark');$('#theme').textContent=document.body.classList.contains('dark')?'☀':'☾'});
document.querySelectorAll('[data-match]').forEach(b=>b.addEventListener('click',()=>update(+b.dataset.match)));
const regions={
'Germany':['€9.1B','~7%','35%',76,'Seed in September, build trial before the October demand peak, then scale the channels and states that pass the repeat and LTV:CAC gates.'],
'Schleswig-Holstein':['3.2%','6%','€30.1k',61,'Build awareness through commuter and coastal wellness venues.'],
'Mecklenburg-Vorpommern':['2.0%','5%','€27.4k',48,'Defer broad launch; test only through tourism and selective DTC.'],
'Hamburg':['10%','7%','€36.8k',78,'Use as a high-income urban test with DTC and office partnerships.'],
'Bremen':['2.1%','6%','€29.4k',54,'Use sampling to learn; keep distribution tightly targeted.'],
'Lower Saxony':['9%','7%','€31.0k',68,'Prioritize Hanover and larger office clusters after Berlin proof.'],
'Brandenburg':['4%','6%','€30.2k',58,'Treat as Berlin spillover; service from the Berlin pilot.'],
'Berlin':['18%','9%','€31.2k',88,'Seed 20–30 workplaces and gym partners, then measure repeat by cohort.'],
'North Rhine-Westphalia':['17%','7%','€32.4k',82,'Largest scale pool; enter after the beachhead proves repeat.'],
'Saxony-Anhalt':['3%','6%','€28.3k',51,'Use grocery only after pricing and repeat gates pass nationally.'],
'Saxony':['6%','7%','€29.1k',63,'Test Leipzig and Dresden with creator-led demand generation.'],
'Thuringia':['3%','6%','€28.6k',50,'Maintain as a later-wave region; prioritize efficient DTC.'],
'Hesse':['8%','7%','€35.1k',75,'Frankfurt office density supports Gym & Office and premium DTC.'],
'Rhineland-Palatinate':['5%','6%','€31.0k',60,'Use regional retail partners after channel economics are validated.'],
'Saarland':['2%','5%','€30.0k',46,'Do not prioritize in the first wave; keep digital-only coverage.'],
'Bavaria':['15%','9%','€37.0k',86,'Munich is the second beachhead; pair premium positioning with DTC.'],
'Baden-Württemberg':['11%','8%','€36.2k',80,'Strong income proxy; activate Stuttgart through performance communities.']};
function showRegion(name){let d=regions[name]||regions.Berlin;document.querySelector('.region.selected')?.classList.remove('selected');document.querySelector(`[data-region="${name}"]`)?.classList.add('selected');$('#regionTitle').textContent=name;$('#regionTag').textContent=d[3]>=80?'priority beachhead':d[3]>=65?'second-wave candidate':'learn later';$('#regionScore').textContent=d[3];$('#regionShare').textContent=d[0];$('#regionCagr').textContent=d[1];$('#regionIncome').textContent=d[2];$('#regionHeadline').textContent=d[3]>=80?'High-priority market':d[3]>=65?'Scale candidate':'Learning market';$('#regionReason').textContent=`Modeled opportunity score ${d[3]}/100. This is a proxy view using market context, income index and city/region growth assumptions.`;$('#regionAction').textContent=d[4]}
document.querySelectorAll('.region').forEach(r=>r.addEventListener('click',()=>showRegion(r.dataset.region)));showRegion('Germany');
$('#reset').addEventListener('click',()=>{mix.value=60;update(2.19);showRegion('Berlin');document.querySelectorAll('.region.selected').forEach(r=>r.classList.remove('selected'))});
function drawGermany(geo){const host=$('#germanyMap'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 620 760');svg.classList.add('geo-map');let coords=[];geo.features.forEach(f=>{const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;polys.forEach(poly=>poly.forEach(ring=>ring.forEach(p=>coords.push(p))))});const xs=coords.map(p=>p[0]),ys=coords.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const pathFor=ring=>ring.map((p,i)=>`${i?'L':'M'}${((p[0]-minX)/(maxX-minX)*560+30).toFixed(1)},${((maxY-p[1])/(maxY-minY)*700+25).toFixed(1)}`).join(' ')+'Z';geo.features.forEach(f=>{const g=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;g.forEach(poly=>{const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',poly.map(pathFor).join(' '));path.classList.add('region');const name=f.properties.name||f.properties.NAME_1||f.properties['name:de'];path.dataset.region=name;path.addEventListener('click',()=>showRegion(name));svg.appendChild(path)})});host.innerHTML='';host.appendChild(svg)}
fetch('germany-states.geojson').then(r=>r.json()).then(drawGermany).catch(()=>{$('#germanyMap').innerHTML='<div class="map-loading">Map boundary file could not be loaded. Please run from a web server.</div>'});
$('#reset').addEventListener('click',()=>{mix.value=60;update(2.19);showRegion('Germany')});
const launch=$('.season-panel');launch.innerHTML='<div class="panel-head"><b>Pre-peak launch plan</b><span>September seed → October demand</span></div><div class="launch-steps"><div><b>SEP</b><strong>Introduce & sample</strong><span>Creators, Gym & Office and DTC waitlist create first taste before peak demand.</span></div><div><b>OCT</b><strong>Convert demand</strong><span>Peak modeled index 122: keep €2.19 visible and optimize for repeat.</span></div><div><b>NOV</b><strong>Scale winners</strong><span>Expand only cohorts with ≥30% repeat and ≥3:1 LTV:CAC.</span></div></div>';
function showRegion(name){let d=regions[name]||regions.Berlin;document.querySelector('.region.selected')?.classList.remove('selected');if(name!=='Germany')document.querySelector(`[data-region="${name}"]`)?.classList.add('selected');$('#regionTitle').textContent=name==='Germany'?'Germany · whole country':name;$('#regionTag').textContent=name==='Germany'?'national view':d[3]>=80?'priority beachhead':d[3]>=65?'second-wave candidate':'learn later';$('#regionScore').textContent=d[3];$('#regionShare').textContent=d[0];$('#regionCagr').textContent=d[1];$('#regionIncome').textContent=d[2];$('#regionHeadline').textContent=name==='Germany'?'National launch thesis':d[3]>=80?'High-priority market':d[3]>=65?'Scale candidate':'Learning market';$('#regionReason').textContent=name==='Germany'?'Germany is the largest next market, but LUMEN should learn in focused beachheads before national distribution.':`Modeled opportunity score ${d[3]}/100. This is a proxy view using market context, income index and city/region growth assumptions.`;$('#regionAction').textContent=d[4]}
setTimeout(()=>document.querySelectorAll('#germanyMap .region').forEach(p=>p.setAttribute('title',p.dataset.region)),1200);
function update(p=+price.value){price.value=p;price2.value=p;const acceptance=Math.max(18,Math.min(68,p<1.9?61.7-(p-1.5)*9:p<2.3?51.7-(p-2.19)*18:26.7-(p-2.59)*6));const retail=.4+(p-1.79)*.575,gym=.81+(p-1.79)*.8,dtc=.77+(p-1.79)*.96,owned=+mix.value/100,profit=owned*((gym+dtc)/2)+(1-owned)*retail,ratio=2.9+(owned-.6)*.4-(Math.abs(p-2.19)*.3),accept=acceptance.toFixed(1);$('#headPrice').textContent=euro(p);$('#priceOut').textContent=euro(p);$('#summaryPrice').textContent=euro(p);$('#acceptance').textContent=accept+'%';$('#profit').textContent=euro(profit);$('#ratio').textContent=ratio.toFixed(1)+'×';$('#mixOut').textContent=mix.value+'% owned';$('#action').textContent=p<2?'Use this only as a time-boxed acquisition offer; protect premium shelf price.':p>2.45?'Reserve this for a premium pack or post-proof upsell.':'Protect '+euro(p)+' and validate repeat before opening grocery distribution.';$('#econTable').innerHTML=[['Retail / Grocery',p*.57,.43,retail],['Gym & Office',p*.87,.13,gym],['DTC Online',p*.96,.04,dtc]].map(r=>`<tr><td>${r[0]}</td><td>${euro(r[1])}</td><td>${(r[2]*100).toFixed(0)}%</td><td class="good">${euro(r[3])}</td></tr>`).join('');const board=document.querySelectorAll('.tile');const mixTile=board[0],profitTile=board[1],positionTile=board[7];mixTile.querySelector('.donut').style.background=`conic-gradient(var(--green) 0 ${owned*100}%,var(--line) ${owned*100}% 100%)`;mixTile.querySelector('.donut span').firstChild.textContent=Math.round(owned*100)+'%';mixTile.querySelector('p').textContent=`${Math.round(owned*100)}% DTC + Gym / ${Math.round((1-owned)*100)}% Grocery`;profitTile.querySelectorAll('i').forEach((el,i)=>{const v=[retail,gym,dtc][i];el.style.height=Math.max(20,Math.min(100,v/1.6*100))+'%';el.textContent=euro(v)});profitTile.querySelector('p').textContent=`Retail ${euro(retail)} · Gym ${euro(gym)} · DTC ${euro(dtc)}`;const pos=p<2.05?'value-led':p<2.4?'premium-accessible':'premium-stretch';positionTile.querySelector('strong').textContent=pos;positionTile.querySelector('p').textContent=`LUMEN at ${euro(p)} vs VoltFit €2.41 and Root & Rise €2.85`;const x=(p-1.5)/1.5*100;$('#brandPin').style.left=x+'%';$('#handle').setAttribute('x1',30+x*5.5);$('#handle').setAttribute('x2',30+x*5.5);$('#fixedLine').setAttribute('d',linePath(t=>.35+.55*t));$('#elasticLine').setAttribute('d',linePath(t=>.2+.78*t-.28*t*t))}
update();
